### ISSUE TITLE
Call to Reset() in generator

### ISSUE THREAD

**Issue by Jellix** [isaahzorgh/PasswordGeneratorAda#1]
You call Reset in each call to Generate. This is wrong, as this would reset the random number generator each time you create a new character. This Reset is based on the current time, so I would be surprised if the returned passwords actually contain random characters. My expectation would be that the passwords contain a repetition of at most two characters.

Also, the conversion to Character is unnecessary, you can instantiate Discrete_Random with a subtype of the Character range you want it to return, e.g.

subtype Password_Characters is range Character'Pos (33) .. Character'Pos (126); and instantiate Discrete_Random with Password_Character as type.

**Comment by isaahzorgh** [comment]
it actually does return random characters 
like this is one output of the programm for the input of 20 
"20s0%%>Q:a)]"y?~,,CYxL" 
so yes in this version the length of the pw is at the start of it BUT there are random characters
I will fix the issue with the length in the next commit

and I will try the subtype 

thanks :)

**Comment by Jellix** [comment]
You're welcome - and don't get me wrong, I'm just trying to help. First steps are always the hardest.

I looked a bit deeper, GNAT bases the random seed on a 64 bit value of clock, so it most likely uses a clock value with nanosecond resolution (at least on Linux), so the values are indeed different with each call. Also, I missed at the first glance, that you instantiate a new Random number generator in each call, which is also not the preferred use. The preferred use in your code would be to instantiate a single instance in the package body and then use that instance to get the next random character.

Happy coding. :)

**Comment by isaahzorgh** [comment]
I am very thankful for the help as I am just starting to code in Ada :D

**Comment by Jellix** [comment]
:+1:  Looks good to me. I think this can be closed. :)
